
pipeline {
    agent any
    options {
        skipStagesAfterUnstable()
    }
     environment {
    }
    stages {
         stage('Clone repository') { 
            steps { 
                script{
                git branch : "master", url : "https://github.com/Udassi-Pawan/devops-backend.git"
                }
            }
        }

        stage('Build') { 
            steps { 
                script{
                 app = docker.build("backend:V$BUILD_NUMBER")
                }
            }
        }
        stage('Test'){
            steps {
                 echo 'Empty'
            }
        }
        stage('Upload Image') {
            steps {
                script{
                        docker.withRegistry('', 'dockerhub') {
                    app.push("V$BUILD_NUMBER")
                    app.push("latest")
                    }
                }
            }
        }
        
        stage('Remove Unused docker image') {
            steps {
                script{
                    sh "docker rmi backend:V$BUILD_NUMBER"
                    }
                }
            }
        
         stage('Deploy Helm chart') {
            steps {
                sh "helm upgrade --install --force backend helm/backend --set appimage=backend:V$BUILD_NUMBER"
            }
        }
        }
    }
}